# Libraries & Display Settings

# Import required libraries for data manipulation and visualization
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Display settings for better readability during analysis
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)
pd.set_option('display.float_format', lambda x: f"{x:.2f}")
df = pd.read_csv(r"C:\Users\isken\OneDrive\Masaüstü\online_retail.csv")

### Data Overview
#Basic inspection of dataset structure, variable types, summary statistics and missing values.

df.info()
df.head()
print(df.dtypes)
print(df.describe().T)
print(df.isnull().sum())

### Date & Customer Check
#Converted date column to datetime format and inspected transaction period and customer availability.

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
print(df["InvoiceDate"])

print(df["InvoiceDate"].min())
print(df["InvoiceDate"].max())

print(df["InvoiceDate"].max() - df["InvoiceDate"].min())

print(df["CustomerID"].count())
print(df["CustomerID"].isnull().sum())

### Removing Missing Customer IDs
#Transactions without CustomerID were removed to ensure customer-level analysis.

rfm_df = df[df["CustomerID"].notnull()]
rfm_df["CustomerID"].count()
rfm_df.isnull().sum()

### Negative Value Check
#Numerical variables were checked for negative values to identify potential returns or data anomalies.

num_cols = [col for col in rfm_df.columns if rfm_df[col].dtypes in ["int64","float64"]]

for col in num_cols:
    print(col, (rfm_df[col] < 0).sum())

### Removing Returns & Creating Basket Price
#Negative quantities were removed to exclude product returns, and total transaction value (BasketPrice) was calculated.

rfm_df = rfm_df[rfm_df["Quantity"] > 0]

rfm_df["BasketPrice"] = rfm_df["Quantity"] * rfm_df["UnitPrice"]

rfm_df

### Customer-Level Aggregation
#Transactions were aggregated at customer level to calculate Monetary value, purchase Frequency, and last purchase date.

rfm_df["CustomerID"].nunique()

rfm_df = rfm_df.groupby("CustomerID").agg(
    Monetary=("BasketPrice", "sum"),
    Frequency=("BasketPrice", "count"),
    Last_Seen=("InvoiceDate", "max")
).reset_index()

rfm_df

### RFM Scoring
#Customers were scored using quantile-based segmentation to assign Recency, Frequency, and Monetary scores.

Recency = [col for col in rfm_df["Last_Seen"]]

Frequency = [col for col in rfm_df["Frequency"]]

Monetary = [col for col in rfm_df["Monetary"]]

rfm_df["R_Score"] = pd.qcut(Recency, 5, labels = [1, 2, 3, 4, 5]).astype(int)

rfm_df["F_Score"] = pd.qcut(Frequency,5, labels = [1, 2, 3, 4, 5]).astype(int)

rfm_df["M_Score"] = pd.qcut(Monetary,5, labels = [1, 2, 3, 4, 5]).astype(int)

rfm_df

### Customer Segmentation
#Customers were categorized into behavioral profiles based on Recency and Frequency scores.

rfm_df["Customer_Profile"] = "Lost Customer"

rfm_df.loc[(rfm_df["R_Score"] >= 4) & (rfm_df["F_Score"] >= 4), "Customer_Profile"] = "Champions"

rfm_df.loc[(rfm_df["R_Score"] >= 4) & (rfm_df["F_Score"] <= 3), "Customer_Profile"] = "New Customer"

rfm_df.loc[(rfm_df["R_Score"] <= 3) & (rfm_df["F_Score"] >= 4), "Customer_Profile"] = "Old Customer"

rfm_df

### Segment Overview
#Customer segment sizes and average monetary scores were examined to understand segment value distribution.

print(rfm_df["Customer_Profile"].value_counts())

rfm_df.groupby("Customer_Profile").agg({"M_Score": "mean"})

### Revenue Contribution by Segment
#Total revenue generated by each customer segment was analyzed to evaluate their business impact.

print(rfm_df.groupby("Customer_Profile").agg({"Monetary": "sum"}).sort_values(by="Monetary", ascending=False))

segment_revenue = rfm_df.groupby("Customer_Profile")["Monetary"].sum()

segment_revenue.sort_values().plot(kind="barh")
plt.title("Revenue Contribution by Customer Segment")
plt.tight_layout()
plt.show()

### Campaign Strategy Assignment
#Personalized marketing campaigns were assigned based on customer segments and monetary value levels.

rfm_df["Campaign_Type"] = "General Offer/Passive"

rfm_df.loc[(rfm_df["Customer_Profile"] == "Champions") & (rfm_df["M_Score"] >=4), "Campaign_Type" ] = "VIP + special advantage"

rfm_df.loc[(rfm_df["Customer_Profile"] == "Champions") & (rfm_df["M_Score"] <=3), "Campaign_Type" ] = "Product Offer + Loyalty Point"

rfm_df.loc[(rfm_df["Customer_Profile"] == "New Customer") & (rfm_df["M_Score"] >=4), "Campaign_Type" ] = "Premium Onboarding + Personal Offer"

rfm_df.loc[(rfm_df["Customer_Profile"] == "New Customer") & (rfm_df["M_Score"] <=3), "Campaign_Type" ] = "Welcome Discount"

rfm_df.loc[(rfm_df["Customer_Profile"] == "Old Customer") & (rfm_df["M_Score"] >=4), "Campaign_Type" ] = "'Miss you' Strong Discount"

rfm_df.loc[(rfm_df["Customer_Profile"] == "Old Customer") & (rfm_df["M_Score"] <=3), "Campaign_Type" ] = "little incentive + Free Shipping"

rfm_df.loc[(rfm_df["Customer_Profile"] == "Lost Customer") & (rfm_df["M_Score"] >=4), "Campaign_Type" ] = "Strong 'Win-Back' Campaign"

rfm_df

rfm_df["Campaign_Type"].value_counts()

df["Country"].value_counts()

### Adding Customer Country Information
#Country information was aggregated at customer level to enrich RFM segmentation analysis.

customer_country = df.groupby("CustomerID")["Country"].first().reset_index()

customer_country

### Merging Country Information
#Customer country data was merged with the RFM table to enable geographic segmentation analysis.

rfm_df = rfm_df.merge(customer_country, on="CustomerID", how="left")

rfm_df

### Geographic Segment Analysis
#Segment distribution was analyzed across countries to identify market-level differences in customer loyalty structure.

rfm_df[rfm_df["Customer_Profile"] == "Champions"]["Country"].value_counts()

countrydist = pd.crosstab(rfm_df["Country"], rfm_df["Customer_Profile"],normalize="index")*100

countrydist

sns.set_theme(rc={"figure.figsize": (12, 10)})
sns.heatmap(countrydist, cmap="RdBu", annot=True, fmt=".1f")
plt.title("Customer Segment Distribution by Country")
plt.tight_layout()
plt.show()

### Revenue Contribution by Country
#Total revenue generated by each country was analyzed to identify key geographic markets.

countrymon = rfm_df.groupby("Country").agg({"Monetary": "sum"}).sort_values(by="Monetary", ascending=False)

countrymon.plot(kind="barh")
plt.title("Revenue Contribution by Country")
plt.tight_layout()
plt.show()


### Customer Loyalty Intensity by Country
#Average frequency scores were compared across countries to evaluate differences in customer loyalty levels.

countryfr = rfm_df.groupby("Country").agg({"F_Score": "mean"}).sort_values(by="F_Score", ascending=False)

plt.scatter(countryfr, countryfr.index)
plt.title("Customer Loyalty Intensity by Country")
plt.tight_layout()
plt.xlabel("Average F Score")
plt.show()

rfm_df